<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>get_android_app</name>
   <tag></tag>
   <elementGuidId>33fd28e0-8326-48a4-9d3a-383c1e53abd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='general-settings__example']//a[@href=&quot;https://play.google.com/store/apps/details?id=com.gurucan.gurucan&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
